name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install apt dependencies
      run: sudo apt-get install -y build-essential libusb-1.0-0-dev pkg-config
    - name: Install rust target
      run: rustup add thumbv7em-none-eabihf
    - name: Install flip-link
      run: cargo install flip-link
    - name: Build
      run: cargo build --release --verbose
